server:
  port: 8080
spring:
  thymeleaf:
    check-template: false
    check-template-location: false

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
